# Generated by Django 5.1.4 on 2026-08-13 12:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Идентификатор филиала')),
                ('slug', models.SlugField(unique=True, verbose_name='Текстовый идентификатор филиала')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
