# Generated by Django 5.1.4 on 2026-08-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchmodel',
            options={'verbose_name': 'Список филиалов', 'verbose_name_plural': 'Список филиалов'},
        ),
        migrations.AlterField(
            model_name='branchmodel',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название филиала'),
        ),
        migrations.AlterField(
            model_name='branchmodel',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Текстовый идентификатор филиала'),
        ),
    ]
