# Generated by Django 5.1.4 on 2026-08-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branchmodel_options_alter_branchmodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchmodel',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True, verbose_name='Текстовый идентификатор филиала'),
        ),
    ]
