# Generated by Django 5.1.4 on 2026-08-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_alter_branchmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchmodel',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Текстовый идентификатор филиала'),
        ),
    ]
