# Generated by Django 5.1.4 on 2026-09-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_alter_branchmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Текстовый идентификатор филиала'),
        ),
    ]
