# Generated by Django 5.1.4 on 2026-07-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='icon_mobile',
            field=models.ImageField(blank=True, upload_to='service_categories/', verbose_name='Иконка (мобильная версия)'),
        ),
    ]
