# Generated by Django 5.1.4 on 2026-09-20 10:26

import apps.common.mixins
import apps.vacancies.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0004_alter_branchmodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Текстовый идентификатор категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Категория вакансии',
                'verbose_name_plural': 'Категории вакансий',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Текстовый идентификатор вакансии')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликована')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('requirements_title', models.CharField(default='Наши обязательные требования', max_length=255, verbose_name='Заголовок обязательных требований')),
                ('partial_requirements_title', models.CharField(default='Будет вашим преимуществом', max_length=255, verbose_name='Заголовок преимуществ')),
                ('responsibilities_title', models.CharField(default='Чем вы будете заниматься', max_length=255, verbose_name='Заголовок обязанностей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branchmodel', verbose_name='Филиал')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='vacancies.vacancycategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['sort_order', 'id'],
            },
            bases=(apps.common.mixins.ImageVariantsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('resume', models.FileField(blank=True, upload_to=apps.vacancies.models.resume_upload_path, verbose_name='Резюме')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('processed', 'Обработана'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус')),
                ('privacy_policy_accepted', models.BooleanField(default=False, verbose_name='Согласие на политику конфиденциальности')),
                ('privacy_policy_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата согласия на политику конфиденциальности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='vacancies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VacancyBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='vacancies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Бейдж вакансии',
                'verbose_name_plural': 'Бейджи вакансии',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VacancyBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='vacancies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Преимущество вакансии',
                'verbose_name_plural': 'Преимущества вакансии',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VacancyBenefitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vacancies/benefits/', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Alt-текст')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_images', to='vacancies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Изображение преимуществ',
                'verbose_name_plural': 'Изображения преимуществ',
                'ordering': ['sort_order', 'id'],
            },
            bases=(apps.common.mixins.ImageVariantsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='VacancyRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('required', 'Обязательное'), ('partial', 'Преимущество')], default='required', max_length=20, verbose_name='Тип требования')),
                ('icon', models.ImageField(blank=True, upload_to='vacancies/icons/', verbose_name='Иконка')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='vacancies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Требование вакансии',
                'verbose_name_plural': 'Требования вакансии',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VacancyResponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='vacancies/responsibilities/', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='vacancies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Обязанность вакансии',
                'verbose_name_plural': 'Обязанности вакансии',
                'ordering': ['sort_order', 'id'],
            },
            bases=(apps.common.mixins.ImageVariantsMixin, models.Model),
        ),
    ]
