# Generated by Django 5.1.4 on 2026-09-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Текстовый идентификатор вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancycategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Текстовый идентификатор категории'),
        ),
    ]
