# Generated by Django 5.1.4 on 2026-08-13 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branchmodel_options_alter_branchmodel_name_and_more'),
        ('consultation', '0002_consultation_page_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='branch_name',
        ),
        migrations.AddField(
            model_name='consultation',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.branchmodel', verbose_name='Филиал'),
        ),
    ]
