# Generated by Django 5.1.4 on 2026-08-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_consultation_is_ad_agreement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='is_ad_agreement',
            field=models.BooleanField(default=False, null=True, verbose_name='Согласие на получение рассылки рекламно-информационных материалов'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='is_privacy_agreement',
            field=models.BooleanField(default=False, verbose_name='Согласие на политику конфиденциальности'),
        ),
    ]
