# Generated by Django 5.1.4 on 2026-07-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_poster_preview_poster_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='poster_mobile',
            field=models.ImageField(blank=True, upload_to='blog/', verbose_name='Постер (мобильная версия)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='preview_poster_mobile',
            field=models.ImageField(blank=True, upload_to='blog/', verbose_name='Превью постера (мобильная версия)'),
        ),
    ]
