# Generated by Django 5.1.4 on 2026-06-24 21:59

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_alter_branch_options_branch_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание')),
                ('banner', models.ImageField(blank=True, upload_to='promotions/', verbose_name='Баннер')),
                ('starts_at', models.DateField(verbose_name='Начало')),
                ('ends_at', models.DateField(blank=True, null=True, verbose_name='Окончание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('branches', models.ManyToManyField(blank=True, related_name='promotions', to='branches.branch', verbose_name='Филиалы')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['-starts_at'],
            },
        ),
    ]
