# Generated by Django 5.1.4 on 2026-07-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='banner_mobile',
            field=models.ImageField(blank=True, upload_to='promotions/', verbose_name='Баннер (мобильная версия)'),
        ),
    ]
