# Generated by Django 5.1.4 on 2026-08-25 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='slug',
            field=models.SlugField(default=0, unique=True, verbose_name='Текстовый идентификатор акции'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PromotionRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255, verbose_name='Имя пациента')),
                ('patient_phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('done', 'Завершена')], default='new', max_length=20, verbose_name='Статус')),
                ('is_ad_agreement', models.BooleanField(default=False, null=True, verbose_name='Согласие на получение рассылки рекламно-информационных материалов')),
                ('is_privacy_agreement', models.BooleanField(default=False, verbose_name='Согласие на политику конфиденциальности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.promotion', verbose_name='Выбранные акции')),
            ],
            options={
                'verbose_name': 'Заявки на консультацию',
                'verbose_name_plural': 'Заявки на консультацию',
                'ordering': ['-created_at'],
            },
        ),
    ]
