# Generated by Django 5.1.4 on 2026-08-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_promotion_slug_promotionrequests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotionrequests',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявки на акцию', 'verbose_name_plural': 'Заявки на акции'},
        ),
        migrations.AlterField(
            model_name='promotion',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Текстовый идентификатор акции'),
        ),
    ]
