# Generated by Django 5.1.4 on 2026-09-28 11:57

import apps.common.mixins
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_alter_promotionrequests_options_alter_promotion_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='conditions_title',
            field=models.CharField(default='Условия акции', max_length=255, verbose_name='Заголовок условий акции'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='detail_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Подробное описание'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='detail_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок подробного описания'),
        ),
        migrations.CreateModel(
            name='PromotionCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, upload_to='promotions/icons/', verbose_name='Иконка')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='promotions.promotion', verbose_name='Акция')),
            ],
            options={
                'verbose_name': 'Условие акции',
                'verbose_name_plural': 'Условия акции',
                'ordering': ['sort_order', 'id'],
            },
            bases=(apps.common.mixins.ImageVariantsMixin, models.Model),
        ),
    ]
