# Generated by Django 5.1.4 on 2026-09-28 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_promotion_conditions_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotioncondition',
            name='icon',
            field=models.FileField(blank=True, help_text='Отдаётся фронтенду как есть, без конвертации. Можно загрузить SVG.', upload_to='promotions/icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp', 'avif'])], verbose_name='Иконка'),
        ),
    ]
