# Generated by Django 5.1.4 on 2026-08-13 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branchmodel_options_alter_branchmodel_name_and_more'),
        ('dms', '0003_remove_dms_branch_name_dms_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dms',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branchmodel', verbose_name='Филиал'),
        ),
    ]
