# Generated by Django 5.1.4 on 2026-08-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0004_alter_dms_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='dms',
            name='is_ad_agreement',
            field=models.BooleanField(default=False, null=True, verbose_name='Согласие на получение рассылки рекламно-информационных материалов'),
        ),
        migrations.AddField(
            model_name='dms',
            name='is_privacy_agreement',
            field=models.BooleanField(default=False, verbose_name='Согласие на политику конфиденциальности'),
        ),
    ]
