# Generated by Django 5.1.4 on 2026-08-12 18:35

import apps.common.mixins
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='Фото')),
                ('photo_mobile', models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='Фото (мобильная версия)')),
                ('bio', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Биография')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('specializations', models.ManyToManyField(blank=True, to='doctors.specialization', verbose_name='Специализации')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
                'ordering': ['last_name', 'first_name'],
            },
            bases=(apps.common.mixins.ImageVariantsMixin, models.Model),
        ),
    ]
