# Generated by Django 5.1.4 on 2026-07-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='Фото (мобильная версия)'),
        ),
    ]
