# Generated by Django 5.1.4 on 2026-06-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name'], 'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.CharField(default='', max_length=500, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='coordinates',
            field=models.JSONField(blank=True, default=dict, verbose_name='Координаты'),
        ),
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='branch',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='phone',
            field=models.CharField(default='', max_length=30, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='working_hours',
            field=models.JSONField(blank=True, default=dict, verbose_name='Часы работы'),
        ),
    ]
