# Generated by Django 5.1.4 on 2026-08-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255, verbose_name='Имя пациента')),
                ('patient_phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('branch_name', models.CharField(choices=[('Landyshevaya 104', 'Ландышевая 104'), ('Volkova 22', 'Волкова 22')], default='Landyshevaya 104', max_length=32, verbose_name='Название филиала')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('done', 'Завершена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Запись на приём',
                'verbose_name_plural': 'Записи на приём',
                'ordering': ['-created_at'],
            },
        ),
    ]
