# Generated by Django 5.1.4 on 2026-08-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='page_url',
            field=models.CharField(default='/', max_length=255, verbose_name='Откуда сделана заявка'),
        ),
    ]
