# Generated by Django 5.1.4 on 2026-08-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='page_url',
            field=models.CharField(blank=True, default='/', max_length=255, verbose_name='Откуда сделана заявка'),
        ),
    ]
