# Generated by Django 5.1.4 on 2026-08-13 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_page_url'),
        ('branch', '0003_alter_branchmodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='branch_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.branchmodel', verbose_name='Филиал'),
        ),
    ]
