# Generated by Django 5.1.4 on 2026-08-13 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_appointment_branch_name_appointment_branch'),
        ('branch', '0003_alter_branchmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branchmodel', verbose_name='Филиал'),
        ),
    ]
